### ISSUE TITLE
Support custom platforms

### ISSUE THREAD

**Issue by lefou** [coursier/dependency#34]
From looking at the Readme, it looks like some platforms like Scala.JS and Scala Native are already supported. It would be nice to have generic platform support, such that other platforms can be parsed as well. That would it make more compatible to the dependency format Mill supports.

Use case: Parse a dependency for a Mill platform (Mill 0.11)

* Mill dependency in platform notation: 
```de.tototec::de.tobiasroeser.mill.vcs.version::0.4.0```

* Java dependency: 
```de.tototec:de.tobiasroeser.mill.vcs.version_mill0.11_2.13:0.4.0```

**Comment by alexarchambault** [comment]
This is already possible. I just [added](https://github.com/coursier/dependency/commit/4749550de4f09fc92f8c1a704d87832abff830bb) a [new paragraph](https://github.com/coursier/dependency/tree/4749550de4f09fc92f8c1a704d87832abff830bb#converting-to-pure-java-dependency-with-a-platform) in the README describing how to do that.
